# markdown
markdown: redcarpet
redcarpet:
  extensions: ["superscript","tables","with_toc_data","strikethrough"]
highlighter: pygments

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Datacenters.cio.gov"
description: "Data Center Optimization Initiative (DCOI)"
baseurl: https://ydave-reisys.github.io/datacenters/
# Uncomment the following line for localhost development at http://127.0.0.1:4000/datacenters/
#baseurl: /datacenters/

# GitHub information
org_name: ydave-reisys
repo_name: datacenters
branch: gh-pages

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /datacenters/
- text: Resources for Agencies
  submenu:
    - text: Inventory Data Submission
      url:  /datacenters/inventory-data-submission/
    - text: DCOI Strategic Plans
      submenu:
        - text: Agency Strategic Plans
          url:  /datacenters/agency-strategic-plan/
        - text: JSON Conversion Tool
          url:  /datacenters/json-conversion-tool/
    - text: Data Center Shared Services
      url:  /datacenters/datacenter-shared-services/
    - text: Contact Information & Community of Practice
      submenu:
        - text: Contact Information
          url:  /datacenters/contact-info/
        - text: Community of Practice
          url: /datacenters/community-practice/
- text: Resources for the Public
  submenu:
    - text: View PDF of Memorandum
      url: /datacenters/assets/documents/memo_16_19_1.pdf
    - text: Implementation & Progress to Date
      url: /datacenters/implementation-and-progress/

# sass
sass:
  sass_dir: _sass
