# markdown
markdown: redcarpet
redcarpet:
  extensions: ["superscript","tables","with_toc_data","strikethrough"]
highlighter: pygments

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Datacenters.cio.gov"
description: "Data Center Optimization Initiative (DCOI)"
baseurl: https://datacenters.cio.gov/
# Uncomment the following line for localhost development at http://127.0.0.1:4000/datacenters/
#baseurl: /datacenters/

# GitHub information
org_name: whitehouse
repo_name: datacenters
branch: gh-pages

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
- text: Resources for Agencies
  submenu:
    - text: Inventory Data Submission
      url:  /inventory-data-submission/
    - text: DCOI Strategic Plans
      submenu:
        - text: Agency Strategic Plans
          url:  /agency-strategic-plan/
        - text: JSON Conversion Tool
          url:  /json-conversion-tool/
        - text: Agency FITARA Milestones Submission
          url:  /milestones/
    - text: Data Center Shared Services
      url:  /datacenter-shared-services/
    - text: Contact Information & Community of Practice
      submenu:
        - text: Contact Information
          url:  /contact-info/
        - text: DCOI Community of Practice
          url: /community-practice/
- text: Resources for the Public
  submenu:
    - text: View PDF of Memorandum
      url: https://www.whitehouse.gov/sites/default/files/omb/memoranda/2016/m_16_19_1.pdf/
    - text: Implementation & Progress to Date
      url: /implementation-and-progress/

# sass
sass:
  sass_dir: _sass
